/**
 * 考研数学一 · 第六章 多元函数积分学 · 练习题库
 *
 * 题目来源：ch06 讲义中的 4 道例题 + 4 道历年真题 + 2 道拓展题
 * 提示内容：按"识别题型 → 选坐标系 → 定上下限 → 算两次积分"逐步揭示
 */
window.PRACTICE_DATA = window.PRACTICE_DATA || {};

window.PRACTICE_DATA['ch06'] = [
    {
        part: '多元',
        type: '直角坐标 · 基础累次',
        source: '例题 1（基础二重积分）',
        difficulty: '★',
        question: '计算 \\(\\displaystyle\\iint_D (x+y)\\,d\\sigma\\)，其中 D = \\{0\\le x\\le 1, 0\\le y\\le 1\\}。',
        hints: [
            '矩形区域 + 多项式被积函数 = 直角坐标最快',
            '先 y 后 x 最直观：每根「竖细条」里的 y 都从 0 到 1',
            '对 y 积分：\\(\\int_0^1 (x+y)\\,dy = \\left[xy+\\dfrac{y^2}{2}\\right]_0^1 = x+\\dfrac{1}{2}\\)',
            '对 x 积分：\\(\\int_0^1 \\left(x+\\dfrac{1}{2}\\right)dx = \\left[\\dfrac{x^2}{2}+\\dfrac{x}{2}\\right]_0^1\\)',
            '**最终答案：\\(I = 1\\)**',
        ],
    },
    {
        part: '多元',
        type: '极坐标 · 圆盘 + x²+y²',
        source: '例题 2（极坐标基础）',
        difficulty: '★★',
        question: '计算 \\(\\displaystyle\\iint_D (x^2+y^2)\\,d\\sigma\\)，其中 D 是圆 \\(x^2+y^2\\le 1\\)。',
        hints: [
            '看到「圆 + 含 x²+y²」立刻想极坐标',
            '极坐标三件套：① \\(x^2+y^2=r^2\\)；② \\(d\\sigma=r\\,dr\\,d\\theta\\)；③ \\(x=r\\cos\\theta, y=r\\sin\\theta\\)',
            '代入：\\(\\iint_D (x^2+y^2)\\,d\\sigma = \\int_0^{2\\pi}d\\theta\\int_0^1 r^2\\cdot r\\,dr = \\int_0^{2\\pi}d\\theta\\int_0^1 r^3\\,dr\\)',
            '⚠️ 那个 r 是 dr 前面那个，绝不能漏',
            '算两个：\\(\\int_0^{2\\pi}d\\theta=2\\pi\\)，\\(\\int_0^1 r^3\\,dr=\\dfrac{1}{4}\\)',
            '相乘：\\(2\\pi\\cdot\\dfrac{1}{4}=\\dfrac{\\pi}{2}\\)',
            '**最终答案：\\(I=\\dfrac{\\pi}{2}\\)**',
        ],
    },
    {
        part: '多元',
        type: '换序 · 不可积信号',
        source: '例题 3（换序基础）',
        difficulty: '★★',
        question: '计算 \\(\\displaystyle\\int_0^1\\!dx\\int_x^1 e^{y^2}\\,dy\\)。提示：先 y 后 x 积分不出，需要换序。',
        hints: [
            '看到 \\(e^{y^2}\\) 这种函数对 y 积分——原函数不是初等的。识别「不可积」是第一步',
            '画区域：D 是「直线 y=x 上方、y=1 下方、x=0 右方」的三角形',
            '改写成「先 x 后 y」：每个 y 对应 x ∈ [0, y]（注意：原题是先 y 后 x 不动；这里是先 x 后 y 版本）',
            '新的积分：\\(\\int_0^1\\!dy\\int_0^y e^{y^2}\\,dx = \\int_0^1 ye^{y^2}\\,dy\\)（对 x 积分时 y 是常数）',
            '换元 u=y²，du=2y dy：\\(\\dfrac{1}{2}\\int_0^1 e^u\\,du = \\dfrac{1}{2}(e-1)\\)',
            '⚠️ 易错：换序时内层上限[0, y]和外层[0,1]要写对',
            '**最终答案：\\(I=\\dfrac{1}{2}(e-1)\\)**',
        ],
    },
    {
        part: '多元',
        type: '对称性 · 奇零偶倍',
        source: '例题 4（对称性基础）',
        difficulty: '★',
        question: '计算 \\(\\displaystyle\\iint_D x\\,y^2\\,d\\sigma\\)，其中 D 由 \\(x=-1, x=1, y=0, y=1\\) 围成（矩形）。',
        hints: [
            '观察区域 D：x 从 -1 到 1，y 从 0 到 1。是关于 y 轴对称的矩形',
            '看被积函数 \\(f(x,y)=xy^2\\)。关于 x 是奇函数（x 取负函数变号）',
            '「奇函数在关于 y 轴对称的区域上 = 0」',
            '⚠️ 注意：要满足两件事：① D 关于 y 轴对称；② f 关于 x 是奇函数',
            '**最终答案：\\(I=0\\)** —— 不需要真算',
        ],
    },
    {
        part: '多元',
        type: '换序 · e^(-x²) 不可积',
        source: '真题 1 | 2017 数一 | 换序',
        difficulty: '★★★',
        question: '计算 \\(\\displaystyle\\int_0^1\\!dy\\int_{\\sqrt{y}}^1 e^{x^2/2}\\,dx\\)。提示：原积分次序算不出，需要换序。',
        hints: [
            '看到 \\(e^{x^2/2}\\) 对 x 积分——原函数不是初等的。换序必有',
            '识别内外层：题中 \\(\\int dy \\int dx\\) 是「先 x 后 y」',
            '画区域 D：y 从 0 到 1，x 从 \\(\\sqrt{y}\\) 到 1。改写：把 \\(\\sqrt{y}\\le x\\) 改成 \\(y\\le x^2\\)',
            '新的 D：\\(0\\le x\\le 1, 0\\le y\\le x^2\\)',
            '改写积分：\\(\\int_0^1\\!dx\\int_0^{x^2} e^{x^2/2}\\,dy\\)（先 y 后 x）',
            '对 y 积分：\\(\\int_0^{x^2} e^{x^2/2}\\,dy = x^2 e^{x^2/2}\\)',
            '分部积分：\\(\\int_0^1 x^2 e^{x^2/2}\\,dx = \\left[xe^{x^2/2}\\right]_0^1 - \\int_0^1 e^{x^2/2}\\,dx\\)',
            '⚠️ 最后那个 \\(\\int_0^1 e^{x^2/2}\\,dx\\) 不是初等积分，留作答案或近似',
            '**最终答案：\\(I=e^{1/2} - \\displaystyle\\int_0^1 e^{x^2/2}\\,dx\\)**',
        ],
    },
    {
        part: '多元',
        type: '直角坐标 · 梯形区域',
        source: '真题 2 | 2020 数一 | 二重积分',
        difficulty: '★★★',
        question: '计算 \\(\\displaystyle\\iint\\limits_D \\dfrac{x^2}{y^2}\\,d\\sigma\\)，其中 D 由 \\(y=x, y=2, x=1\\) 围成。',
        hints: [
            '画图：三条线围成一个上宽下窄的梯形，x ∈ [1, 2]，y ∈ [x, 2]',
            '选择积分次序：被积函数 \\(1/y^2\\) 对 y 积分得 \\(-1/y\\)，很干净 → 先 y 后 x',
            '化为累次积分：\\(I = \\int_1^2\\!dx\\int_x^2 \\dfrac{x^2}{y^2}\\,dy\\)',
            '对 y 积分（x 当常数）：\\(\\int_x^2 \\dfrac{x^2}{y^2}\\,dy = x^2\\cdot\\left[-\\dfrac{1}{y}\\right]_x^2 = x^2\\left(-\\dfrac{1}{2}+\\dfrac{1}{x}\\right)=x-\\dfrac{x^2}{2}\\)',
            '⚠️ 易错：\\(-1/y\\) 的负号容易漏；或忘了代入 y=x',
            '对 x 积分：\\(I = \\int_1^2 \\left(x-\\dfrac{x^2}{2}\\right)dx = \\left[\\dfrac{x^2}{2}-\\dfrac{x^3}{6}\\right]_1^2\\)',
            '代入：\\(\\left(2-\\dfrac{8}{6}\\right)-\\left(\\dfrac{1}{2}-\\dfrac{1}{6}\\right)=\\dfrac{2}{3}-\\dfrac{1}{3}=\\dfrac{1}{3}\\)',
            '**最终答案：\\(I=\\dfrac{1}{3}\\)**',
        ],
    },
    {
        part: '多元',
        type: '极坐标 · 圆方程转 r',
        source: '真题 3 | 2019 数一 | 圆盘积分',
        difficulty: '★★★',
        question: '计算 \\(\\displaystyle\\iint\\limits_D (x^2+y^2)\\,d\\sigma\\)，其中 D 由 \\(x^2+y^2=2x\\) 围成。',
        hints: [
            '看到「圆」+「x²+y²」立刻想极坐标',
            '极坐标转换：\\(x^2+y^2=r^2, x=r\\cos\\theta\\)。代入圆方程：\\(r^2=2r\\cos\\theta \\Rightarrow r=2\\cos\\theta\\)',
            '这是一条过原点的圆（圆心在 (1,0)，半径 1）',
            'θ 范围：r ≥ 0 要求 \\(\\cos\\theta \\ge 0\\)，即 \\(\\theta\\in[-\\pi/2, \\pi/2]\\)',
            '化为累次积分：\\(I=\\int_{-\\pi/2}^{\\pi/2}d\\theta\\int_0^{2\\cos\\theta} r^3\\,dr\\)',
            '⚠️ 那个 r 是 dr 前面那个！位置极其重要',
            '对 r 积分：\\(\\int_0^{2\\cos\\theta} r^3\\,dr = \\dfrac{(2\\cos\\theta)^4}{4} = 4\\cos^4\\theta\\)',
            '对 θ 积分：用对称性，只算 \\([0, \\pi/2]\\) 乘 2；再用降幂公式 \\(\\cos^4\\theta=\\dfrac{3+4\\cos 2\\theta+\\cos 4\\theta}{8}\\)',
            '\\(\\int_0^{\\pi/2}\\cos^4\\theta\\,d\\theta = \\dfrac{3}{8}\\cdot\\dfrac{\\pi}{2}=\\dfrac{3\\pi}{16}\\)',
            '最终：\\(I=2\\cdot 4\\cdot \\dfrac{3\\pi}{16}=\\dfrac{3\\pi}{2}\\)',
            '**最终答案：\\(I=\\dfrac{3\\pi}{2}\\)**',
        ],
    },
    {
        part: '多元',
        type: '绝对值 + 对称性',
        source: '真题 4 | 2022 数一 | 绝对值',
        difficulty: '★★★',
        question: '计算 \\(\\displaystyle\\iint\\limits_D |x-y|\\,d\\sigma\\)，其中 D：\\(0\\le x\\le 1, 0\\le y\\le 1\\)。',
        hints: [
            '看到绝对值 \\(|x-y|\\)，先识别「分两段」：把方块分成 \\(D_1: x\\ge y\\) 和 \\(D_2: y>x\\) 两个三角',
            '去掉绝对值：在 \\(D_1\\) 里 \\(|x-y|=x-y\\)，在 \\(D_2\\) 里 \\(|x-y|=y-x\\)',
            '⚠️ 易错：直接对绝对值积分是错的，必须先分段',
            '利用对称性：D 关于直线 y=x 对称，所以 \\(D_1\\) 和 \\(D_2\\) 积分相等（轮换对称）',
            '只需算一个：\\(I = 2\\iint_{D_1}(x-y)\\,d\\sigma = 2\\int_0^1\\!dx\\int_0^x (x-y)\\,dy\\)',
            '对 y 积分：\\(\\int_0^x(x-y)\\,dy = \\left[xy-\\dfrac{y^2}{2}\\right]_0^x = \\dfrac{x^2}{2}\\)',
            '对 x 积分：\\(I = 2\\int_0^1 \\dfrac{x^2}{2}\\,dx = \\int_0^1 x^2\\,dx = \\dfrac{1}{3}\\)',
            '**最终答案：\\(I=\\dfrac{1}{3}\\)**',
        ],
    },
    {
        part: '多元',
        type: '直角坐标 · 抛物线区域',
        source: '拓展题 1 | 抛物线区域',
        difficulty: '★★',
        question: '计算 \\(\\displaystyle\\iint\\limits_D xy\\,d\\sigma\\)，其中 D 由 \\(y=x\\) 与 \\(y=x^2\\) 围成（两曲线相交区域）。',
        hints: [
            '画图：\\(y=x\\) 是直线，\\(y=x^2\\) 是抛物线。两条曲线交于 (0,0) 和 (1,1)',
            '在 (0,1) 区间内，\\(y=x\\) 在 \\(y=x^2\\) 上方（因为 x vs x² 在 (0,1) 上 x > x²）',
            '所以 D：0 ≤ x ≤ 1，x² ≤ y ≤ x',
            '化成累次积分：\\(I = \\int_0^1\\!dx\\int_{x^2}^x xy\\,dy\\)',
            '对 y 积分：\\(\\int_{x^2}^x xy\\,dy = x\\left[\\dfrac{y^2}{2}\\right]_{x^2}^x = x\\cdot\\dfrac{1}{2}\\left(x^2-x^4\\right)=\\dfrac{x^3-x^5}{2}\\)',
            '⚠️ 易错：\\(y=x^2\\) 时不能漏减 \\(y=x\\) 那部分',
            '对 x 积分：\\(I=\\dfrac{1}{2}\\int_0^1(x^3-x^5)\\,dx=\\dfrac{1}{2}\\left[\\dfrac{x^4}{4}-\\dfrac{x^6}{6}\\right]_0^1=\\dfrac{1}{2}\\cdot\\dfrac{1}{12}=\\dfrac{1}{24}\\)',
            '**最终答案：\\(I=\\dfrac{1}{24}\\)**',
        ],
    },
    {
        part: '多元',
        type: '对称性 · 圆形区域',
        source: '拓展题 2 | 圆盘对称性',
        difficulty: '★★',
        question: '计算 \\(\\displaystyle\\iint\\limits_D e^{-(x^2+y^2)}\\,d\\sigma\\)，其中 D 是圆 \\(x^2+y^2\\le R^2\\)。',
        hints: [
            '圆 + 指数函数 = 极坐标（极坐标下 \\(x^2+y^2=r^2\\)）',
            '极坐标代入：\\(e^{-(x^2+y^2)}\\to e^{-r^2}\\)，\\(d\\sigma=r\\,dr\\,d\\theta\\)',
            '化为：\\(I=\\int_0^{2\\pi}d\\theta\\int_0^R e^{-r^2}\\cdot r\\,dr\\)',
            '对 r 积分：\\(\\int_0^R re^{-r^2}\\,dr\\)。令 \\(u=-r^2\\)，\\(du=-2r\\,dr\\)',
            '得：\\(-\\dfrac{1}{2}\\int_0^{-R^2} e^u\\,du = \\dfrac{1}{2}\\int_{-R^2}^0 e^u\\,du = \\dfrac{1}{2}(1-e^{-R^2})\\)',
            '⚠️ 易错：换元时符号容易乱；r 那个系数很容易被忽略',
            '对 θ 积分：\\(I=2\\pi\\cdot\\dfrac{1}{2}(1-e^{-R^2}) = \\pi(1-e^{-R^2})\\)',
            '**最终答案：\\(I=\\pi(1-e^{-R^2})\\)** —— 这个结果在概率论（2D 正态）中很重要',
        ],
    },
];
