-- 单词第二批（50 个常用高频词）
INSERT INTO words (word, phonetic, meaning, example_sentence, example_translation, part_of_speech, difficulty, category) VALUES
('authority', '/ɔːˈθɔːrəti/', '权威，权力', 'The government has the authority to make decisions.', '政府有权做出决定。', 'n.', 4, '高频核心'),
('concept', '/ˈkɑːnsept/', '概念，观念', 'The concept of equality is fundamental.', '平等的概念是基本的。', 'n.', 3, '高频核心'),
('consistent', '/kənˈsɪstənt/', '一致的，始终如一的', 'Be consistent in your efforts.', '坚持不懈地努力。', 'adj.', 4, '高频核心'),
('constitute', '/ˈkɑːnstətuːt/', '构成，组成', 'Women constitute half of the population.', '女性占总人口的一半。', 'v.', 4, '高频核心'),
('context', '/ˈkɑːntekst/', '背景，环境', 'Consider the historical context of the event.', '考虑事件的历史背景。', 'n.', 3, '高频核心'),
('contract', '/ˈkɑːntrækt/', '合同，契约', 'Read the contract carefully before signing.', '签字前仔细阅读合同。', 'n./v.', 4, '高频核心'),
('create', '/kriˈeɪt/', '创造', 'Artists create works that move people.', '艺术家创作出打动人的作品。', 'v.', 2, '高频核心'),
('culture', '/ˈkʌltʃər/', '文化', 'Every culture has its unique traditions.', '每种文化都有其独特的传统。', 'n.', 3, '高频核心'),
('data', '/ˈdeɪtə/', '数据', 'Data analysis is essential for decision-making.', '数据分析对决策至关重要。', 'n.', 2, '高频核心'),
('define', '/dɪˈfaɪn/', '定义，明确', 'Please define the key terms.', '请定义关键术语。', 'v.', 3, '高频核心'),
('deliver', '/dɪˈlɪvər/', '交付，传递', 'We deliver orders within 24 hours.', '我们在 24 小时内送达订单。', 'v.', 3, '高频核心'),
('design', '/dɪˈzaɪn/', '设计', 'The building was designed by a famous architect.', '这座建筑由著名建筑师设计。', 'v./n.', 3, '高频核心'),
('diversity', '/daɪˈvɜːrsəti/', '多样性', 'Cultural diversity enriches society.', '文化多样性丰富了社会。', 'n.', 4, '高频核心'),
('efficient', '/ɪˈfɪʃnt/', '高效的', 'This new system is more efficient.', '这个新系统更高效。', 'adj.', 3, '高频核心'),
('emerge', '/iˈmɜːrdʒ/', '出现，浮现', 'New problems emerged during the process.', '过程中出现了新问题。', 'v.', 4, '高频核心'),
('emphasis', '/ˈemfəsɪs/', '强调', 'The report puts emphasis on safety.', '报告强调安全。', 'n.', 4, '高频核心'),
('ensure', '/ɪnˈʃʊr/', '确保', 'Please ensure that all windows are closed.', '请确保所有窗户都关好。', 'v.', 3, '高频核心'),
('environment', '/ɪnˈvaɪrənmənt/', '环境', 'We must protect the environment.', '我们必须保护环境。', 'n.', 3, '高频核心'),
('essential', '/ɪˈsenʃl/', '必要的，本质的', 'Water is essential for life.', '水是生命的必需品。', 'adj.', 3, '高频核心'),
('evaluate', '/ɪˈvæljueɪt/', '评估', 'Teachers evaluate students regularly.', '老师定期评估学生。', 'v.', 4, '高频核心'),
('evident', '/ˈevɪdənt/', '明显的', 'It is evident that he is lying.', '很明显他在撒谎。', 'adj.', 4, '高频核心'),
('factor', '/ˈfæktər/', '因素', 'Several factors contribute to success.', '多种因素促成成功。', 'n.', 3, '高频核心'),
('feature', '/ˈfiːtʃər/', '特征，特色', 'Safety is a key feature of this car.', '安全是这款车的主要特色。', 'n.', 3, '高频核心'),
('finance', '/ˈfaɪnæns/', '财政，金融', 'Personal finance is important.', '个人理财很重要。', 'n.', 4, '高频核心'),
('flexible', '/ˈfleksəbl/', '灵活的', 'Be flexible in your thinking.', '思维要灵活。', 'adj.', 3, '高频核心'),
('formula', '/ˈfɔːrmjələ/', '公式，方案', 'There is no magic formula for success.', '成功没有神奇的公式。', 'n.', 3, '高频核心'),
('function', '/ˈfʌŋkʃn/', '功能，作用', 'What is the function of this button?', '这个按钮的作用是什么？', 'n.', 3, '高频核心'),
('fundamental', '/ˌfʌndəˈmentl/', '基本的，根本的', 'Honesty is a fundamental virtue.', '诚实是基本美德。', 'adj.', 4, '高频核心'),
('global', '/ˈɡloʊbl/', '全球的', 'Climate change is a global issue.', '气候变化是全球性问题。', 'adj.', 3, '高频核心'),
('impact', '/ˈɪmpækt/', '影响，冲击', 'The policy had a major impact on the economy.', '该政策对经济产生了重大影响。', 'n./v.', 3, '高频核心'),
('implement', '/ˈɪmplɪment/', '实施', 'Implement the plan step by step.', '逐步实施计划。', 'v.', 4, '高频核心'),
('imply', '/ɪmˈplaɪ/', '暗示，意味着', 'What are you implying?', '你暗示什么？', 'v.', 4, '高频核心'),
('income', '/ˈɪnkʌm/', '收入', 'Their main source of income is tourism.', '他们的主要收入来源是旅游业。', 'n.', 3, '高频核心'),
('indicate', '/ˈɪndɪkeɪt/', '表明，指出', 'The data indicates a rising trend.', '数据表明趋势在上升。', 'v.', 3, '高频核心'),
('industry', '/ˈɪndəstri/', '工业，行业', 'The film industry is growing fast.', '电影业发展迅速。', 'n.', 3, '高频核心'),
('influence', '/ˈɪnfluəns/', '影响', 'Social media influences our opinions.', '社交媒体影响我们的观点。', 'n./v.', 3, '高频核心'),
('integrate', '/ˈɪntɪɡreɪt/', '整合，使结合', 'Integrate new ideas into the plan.', '把新想法融入计划。', 'v.', 4, '高频核心'),
('interpret', '/ɪnˈtɜːrprɪt/', '解释，解读', 'How do you interpret this poem?', '你如何解读这首诗？', 'v.', 4, '高频核心'),
('issue', '/ˈɪʃuː/', '问题，议题', 'This is a serious issue.', '这是一个严重的问题。', 'n.', 3, '高频核心'),
('labor', '/ˈleɪbər/', '劳动', 'Hard labor builds character.', '辛勤劳动塑造品格。', 'n.', 4, '高频核心'),
('language', '/ˈlæŋɡwɪdʒ/', '语言', 'Language is a tool for communication.', '语言是交流的工具。', 'n.', 2, '高频核心'),
('legal', '/ˈliːɡl/', '合法的，法定的', 'Is this action legal?', '这个行为合法吗？', 'adj.', 3, '高频核心'),
('link', '/lɪŋk/', '联系，连接', 'There is a link between the two events.', '两件事之间有联系。', 'n./v.', 2, '高频核心'),
('locate', '/ˈloʊkeɪt/', '定位，位于', 'The store is located downtown.', '商店位于市中心。', 'v.', 3, '高频核心'),
('method', '/ˈmeθəd/', '方法', 'This is an effective method.', '这是一种有效的方法。', 'n.', 3, '高频核心'),
('obtain', '/əbˈteɪn/', '获得', 'You need to obtain a permit first.', '你需要先获得许可。', 'v.', 4, '高频核心'),
('occur', '/əˈkɜːr/', '发生', 'The accident occurred last night.', '事故发生在昨晚。', 'v.', 3, '高频核心'),
('participate', '/pɑːrˈtɪsɪpeɪt/', '参与', 'Everyone can participate in the event.', '每个人都可以参与本次活动。', 'v.', 4, '高频核心');

-- 单词第三批（核心动词与形容词）
INSERT INTO words (word, phonetic, meaning, example_sentence, example_translation, part_of_speech, difficulty, category) VALUES
('perceive', '/pərˈsiːv/', '感知，理解', 'How do you perceive the world?', '你如何理解这个世界？', 'v.', 4, '高频核心'),
('percent', '/pərˈsent/', '百分比', 'Twenty percent of students passed.', '20% 的学生通过了。', 'n.', 2, '高频核心'),
('period', '/ˈpɪriəd/', '时期', 'This is a period of rapid change.', '这是一个快速变化的时期。', 'n.', 2, '高频核心'),
('policy', '/ˈpɑːləsi/', '政策', 'The new policy took effect in June.', '新政策于 6 月生效。', 'n.', 3, '高频核心'),
('positive', '/ˈpɑːzətɪv/', '积极的，正面的', 'Keep a positive attitude.', '保持积极的态度。', 'adj.', 3, '高频核心'),
('previous', '/ˈpriːviəs/', '以前的', 'I met him on a previous occasion.', '我上次见过他。', 'adj.', 3, '高频核心'),
('primary', '/ˈpraɪmeri/', '主要的', 'Reading is his primary source of knowledge.', '阅读是他获取知识的主要途径。', 'adj.', 3, '高频核心'),
('principle', '/ˈprɪnsəpl/', '原则，原理', 'Stick to your principles.', '坚持你的原则。', 'n.', 4, '高频核心'),
('professional', '/prəˈfeʃənl/', '专业的', 'He is a professional photographer.', '他是一位专业摄影师。', 'adj./n.', 3, '高频核心'),
('proportion', '/prəˈpɔːrʃn/', '比例', 'A large proportion of students disagree.', '很大比例的学生不同意。', 'n.', 4, '高频核心'),
('publish', '/ˈpʌblɪʃ/', '出版，发表', 'She published her first book last year.', '她去年出版了第一本书。', 'v.', 3, '高频核心'),
('purchase', '/ˈpɜːrtʃəs/', '购买', 'We plan to purchase a new car.', '我们计划购买一辆新车。', 'v./n.', 3, '高频核心'),
('pursue', '/pərˈsuː/', '追求', 'Pursue your dreams with passion.', '充满激情地追求你的梦想。', 'v.', 4, '高频核心'),
('range', '/reɪndʒ/', '范围，幅度', 'Prices range from $10 to $100.', '价格在 10 到 100 美元之间。', 'n.', 3, '高频核心'),
('rare', '/rer/', '稀有的', 'It is rare to see snow here.', '在这里看到雪很罕见。', 'adj.', 3, '高频核心'),
('react', '/riˈækt/', '反应', 'How did she react to the news?', '她对这个消息有什么反应？', 'v.', 3, '高频核心'),
('reform', '/rɪˈfɔːrm/', '改革', 'Education reform is necessary.', '教育改革是必要的。', 'n./v.', 4, '高频核心'),
('region', '/ˈriːdʒən/', '地区', 'This region is famous for its wine.', '该地区以葡萄酒闻名。', 'n.', 3, '高频核心'),
('regulate', '/ˈreɡjuleɪt/', '监管，调节', 'The industry is strictly regulated.', '该行业受到严格监管。', 'v.', 4, '高频核心'),
('reject', '/rɪˈdʒekt/', '拒绝', 'Please do not reject this proposal.', '请不要拒绝这个提议。', 'v.', 3, '高频核心'),
('relevant', '/ˈreləvənt/', '相关的', 'Please send me relevant documents.', '请把相关文件发给我。', 'adj.', 3, '高频核心'),
('rely', '/rɪˈlaɪ/', '依赖，依靠', 'You can rely on him.', '你可以依靠他。', 'v.', 3, '高频核心'),
('remove', '/rɪˈmuːv/', '移除', 'Please remove your shoes before entering.', '请脱鞋后再进入。', 'v.', 2, '高频核心'),
('require', '/rɪˈkwaɪər/', '需要', 'All passengers are required to wear masks.', '所有乘客必须戴口罩。', 'v.', 3, '高频核心'),
('research', '/rɪˈsɜːrtʃ/', '研究', 'Scientific research drives progress.', '科学研究推动进步。', 'n./v.', 3, '高频核心'),
('resolve', '/rɪˈzɑːlv/', '解决', 'We must resolve this conflict quickly.', '我们必须尽快解决冲突。', 'v.', 4, '高频核心'),
('respond', '/rɪˈspɑːnd/', '回应', 'She did not respond to my email.', '她没有回复我的邮件。', 'v.', 3, '高频核心'),
('restrain', '/rɪˈstreɪn/', '抑制，约束', 'Try to restrain your anger.', '尽量克制你的愤怒。', 'v.', 4, '高频核心'),
('reveal', '/rɪˈviːl/', '揭示', 'The study reveals new evidence.', '这项研究揭示了新证据。', 'v.', 3, '高频核心'),
('role', '/roʊl/', '角色，作用', 'He plays an important role in the team.', '他在团队中扮演重要角色。', 'n.', 2, '高频核心'),
('section', '/ˈsekʃn/', '部分，章节', 'Please read this section carefully.', '请仔细阅读这一部分。', 'n.', 3, '高频核心'),
('seek', '/siːk/', '寻求', 'He is seeking a new job.', '他正在寻找新工作。', 'v.', 3, '高频核心'),
('select', '/sɪˈlekt/', '选择', 'Select the best candidate.', '挑选最佳候选人。', 'v.', 3, '高频核心'),
('shift', '/ʃɪft/', '转移，转变', 'There has been a shift in public opinion.', '公众舆论发生了转变。', 'v./n.', 3, '高频核心'),
('similar', '/ˈsɪmələr/', '相似的', 'We have similar interests.', '我们有相似的兴趣。', 'adj.', 2, '高频核心'),
('society', '/səˈsaɪəti/', '社会', 'Modern society faces many challenges.', '现代社会面临诸多挑战。', 'n.', 3, '高频核心'),
('specific', '/spəˈsɪfɪk/', '具体的', 'Please give a specific example.', '请给出具体例子。', 'adj.', 3, '高频核心'),
('status', '/ˈsteɪtəs/', '地位，状态', 'Check the status of your order.', '查看你的订单状态。', 'n.', 3, '高频核心'),
('stress', '/stres/', '压力，强调', 'Stress can affect your health.', '压力会影响健康。', 'n./v.', 3, '高频核心'),
('structure', '/ˈstrʌktʃər/', '结构', 'The building has a strong structure.', '这座建筑结构坚固。', 'n.', 3, '高频核心'),
('sufficient', '/səˈfɪʃnt/', '足够的', 'We have sufficient evidence.', '我们有足够的证据。', 'adj.', 4, '高频核心'),
('supply', '/səˈplaɪ/', '供应', 'Supply cannot meet demand.', '供不应求。', 'v./n.', 3, '高频核心'),
('survive', '/sərˈvaɪv/', '幸存', 'Only a few plants survive the winter.', '只有少数植物能越冬。', 'v.', 3, '高频核心'),
('target', '/ˈtɑːrɡɪt/', '目标', 'Set a clear target for yourself.', '为自己设定一个明确的目标。', 'n./v.', 3, '高频核心'),
('trend', '/trend/', '趋势', 'This is a growing trend.', '这是一个日益增长的趋势。', 'n.', 3, '高频核心'),
('ultimate', '/ˈʌltɪmət/', '最终的', 'Our ultimate goal is success.', '我们最终的目标是成功。', 'adj.', 4, '高频核心'),
('undergo', '/ˌʌndərˈɡoʊ/', '经历', 'The company underwent major changes.', '公司经历了重大变革。', 'v.', 4, '高频核心'),
('unique', '/juˈniːk/', '独特的', 'Every person is unique.', '每个人都是独特的。', 'adj.', 3, '高频核心'),
('vary', '/ˈveri/', '变化', 'Opinions vary from person to person.', '意见因人而异。', 'v.', 3, '高频核心'),
('widespread', '/ˈwaɪdspred/', '广泛的', 'The rumor was widespread.', '谣言流传很广。', 'adj.', 4, '高频核心');

-- 长难句第二批
INSERT INTO long_sentences (english, chinese, analysis, grammar_points, key_vocabulary, source, difficulty) VALUES
(
  'It is a truth universally acknowledged that a single man in possession of a good fortune must be in want of a wife.',
  '凡有产业的单身汉，总想娶位太太，这是一条举世公认的真理。',
  '主语从句：that a single man...a wife 是 truth 的同位语从句，强调结构：It is...that。',
  '主语从句、强调句型、固定搭配',
  ARRAY['acknowledged: 公认的', 'possession: 拥有', 'in want of: 需要'],
  '《傲慢与偏见》开篇名句',
  4
),
(
  'Not only did the scientist discover a new species, but he also established a whole new field of research that has since attracted scholars worldwide.',
  '这位科学家不仅发现了一个新物种，还开创了一个全新的研究领域，吸引了世界各地的学者。',
  '倒装句：Not only 置于句首时，主句部分倒装 did the scientist；that 引导定语从句修饰 field。',
  '倒装句、定语从句、固定搭配 not only...but also',
  ARRAY['species: 物种', 'establish: 创立', 'attract: 吸引'],
  '考研英语一·常见句型',
  4
),
(
  'Had the government invested more in public transportation, the current traffic congestion in major cities would have been significantly alleviated.',
  '如果政府在公共交通上投入更多资金，主要城市当前的交通拥堵问题将会得到显著缓解。',
  '虚拟语气：Had the government... 是省略 if 的倒装虚拟条件句，相当于 If the government had invested...。',
  '虚拟语气、倒装句、省略 if',
  ARRAY['invest: 投资', 'congestion: 拥堵', 'alleviate: 缓解'],
  '考研英语一·常见句型',
  5
),
(
  'The professor argued that the experiment, however brilliant in design, was doomed to fail because it ignored fundamental psychological factors that govern human behavior.',
  '教授认为，尽管这个实验设计精妙，但由于忽略了支配人类行为的基本心理因素，它注定要失败。',
  '宾语从句：that the experiment...govern human behavior；however 引导让步状语；because 引导原因状语从句；that govern human behavior 是定语从句修饰 factors。',
  '宾语从句、让步状语、原因状语、定语从句',
  ARRAY['brilliant: 精妙的', 'be doomed to: 注定', 'fundamental: 基本的'],
  '考研英语一·常见句型',
  4
),
(
  'What surprises researchers most is not that the brain produces new neurons in adulthood, but that the rate at which they are produced can be influenced by lifestyle choices.',
  '最令研究人员惊讶的不是成年人的大脑会产生新的神经元，而是新神经元的产生速率会受到生活方式选择的影响。',
  '主语从句：What surprises researchers most；表语从句：not that..., but that...；定语从句：at which they are produced 修饰 the rate。',
  '主语从句、表语从句、定语从句、固定搭配 not that...but that',
  ARRAY['neuron: 神经元', 'adulthood: 成年', 'lifestyle: 生活方式'],
  '考研英语一·2024年·阅读',
  5
);